### ISSUE TITLE
Advice: You can use lazy val to run heavy initialization once per executor

### ISSUE THREAD

**Issue by i10416** [WorksApplications/uzushio#12]
Sorry in advance if I missed something, but I think you can take advantage of Scala's lazy val feature to run heavy initialization once per executor with regards to https://github.com/WorksApplications/uzushio/blob/main/src/main/scala/com/worksap/nlp/uzushio/SudachiTokenizer.scala and https://github.com/WorksApplications/uzushio/blob/main/src/main/scala/com/worksap/nlp/uzushio/Sudachi.scala.

For example,

```scala
object Registry {
  lazy val instance = {
    val settings =
      s"""|{
          |  "systemDict" : "/hdfs/path/to/sudachi/20230110/system_core.dic",
          |  "oovProviderPlugin" : [
          |    {
          |      "class" : "com.worksap.nlp.sudachi.SimpleOovProviderPlugin",
          |      "oovPOS" : [ "名詞", "普通名詞", "一般", "*", "*", "*"]
          |    }
          |  ]
          |}""".stripMargin
    (new DictionaryFactory).create(
      sudachi.Config.fromJsonString(settings, sudachi.PathAnchor.none())
    ).create()
  }
}


df
  .select("<text col>")
  .as[String]
  .map(str => Registry.instance.tokenize(str).asScala.map(_.surface))
   ...
```

See the following figure to check executor computing time.

![image](https://github.com/WorksApplications/uzushio/assets/39330037/93d83c71-bfc5-4b08-81f8-3a861942e937)

**Comment by eiennohito** [comment]
Sudachi is used only in legacy filters and is not used in the current version. It will be removed at the some time point (when the new filter pipeline will be more or less feature complete).
