### ISSUE TITLE
sbt assembly aggregating for all subprojects is incorrect

### ISSUE THREAD

**Issue by eiennohito** [WorksApplications/uzushio#17]
Because of project aggregating, `sbt assembly` from the root project tries to assembly everything, which is incorrect.

@i10416 `sbt assembly` from the root project should redirect to assembly task of `core` project, can you please fix it?

**Comment by i10416** [comment]
Sorry for the mess. I'll look into it.

**Comment by i10416** [comment]
BTW, you can run assembly command for subproject using `core/assembly`

**Comment by eiennohito** [comment]
Yep, I know that, but assembly does not make sense for other projects (and OOMs sbt's JVM on -Xmx=1G)

**Comment by i10416** [comment]
Ah, that's right.
